Repository Good-MoGong/SYM, pull requests merged in 2024-03, with the labels that each got.

#119 Refactor, feat: 각종 필드 크기 수정, 유저 아이디, 프로바이더 정보 가져오기 적용 Oz/#89
  Projects/App/Sources/DesignSystem/ChatBubble/ChatBubble.swift
  Projects/App/Sources/DesignSystem/Common/CustomNavigationBar.swift
  Projects/App/Sources/DesignSystem/Common/ProgressView.swift
  Projects/App/Sources/DesignSystem/Common/RecordView.swift
  Projects/App/Sources/Domain/UseCases/Protocol/Services/AuthenticationService.swift
  Projects/App/Sources/Presentation/Authencation/AuthenticatedViewModel.swift
  Projects/App/Sources/Presentation/Calendar/View/DatePicker.swift
  Projects/App/Sources/Presentation/MyPage/MyAccountInfo.swift
  Projects/App/Sources/Presentation/MyPage/MypageView.swift
  Projects/App/Sources/Presentation/MyPage/SettingView.swift
  Projects/App/Sources/Presentation/Record/Views/RecordCompletionView.swift
Labels: 🪄Feat, 😎Refactor, 🙊상필

#122 Fix, Feat: Local Notification 수정 완료 및 미래 날짜 선택 시 toast view 추가
  Projects/App/Sources/DesignSystem/Form/TextEditor.swift
  Projects/App/Sources/Domain/UseCases/Protocol/Services/PushNotificationService.swift
  Projects/App/Sources/Model/Alarm.swift
  Projects/App/Sources/Presentation/Alarm/AlarmMainView.swift
  Projects/App/Sources/Presentation/Authencation/AuthenticatedView.swift
  Projects/App/Sources/Presentation/Calendar/View/CalendarDetailView.swift
  Projects/App/Sources/Presentation/Calendar/View/CalendarMainView.swift
  Projects/App/Sources/Presentation/Calendar/ViewModel/CalendarViewModel.swift
  Projects/App/Sources/Presentation/Tab/MainTab.swift
  Projects/App/Sources/Presentation/Tab/TabBarView.swift
  Projects/App/Sources/SYMApp.swift
  Projects/App/Support/Info.plist
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  Tuist/ProjectDescriptionHelpers/Target+Templates.swift
Labels: 🪄Feat, ✨Fix, 🐶서연

#129 Fix, Refactor: #126 pr conflict 해결 및 AuthService, Viewmodel 리팩토링
  .tuist-version
  Projects/App/Sources/DesignSystem/Common/RecordView.swift
  Projects/App/Sources/Domain/UseCases/Protocol/Services/AuthenticationService.swift
  Projects/App/Sources/Domain/UseCases/Protocol/Services/FirebaseService.swift
  Projects/App/Sources/Presentation/Authencation/AuthenticatedView.swift
  Projects/App/Sources/Presentation/Authencation/AuthenticatedViewModel.swift
  Projects/App/Sources/Presentation/Calendar/View/CalendarDetailView.swift
  Projects/App/Sources/Presentation/Login/View/LoginIntroView.swift
  Projects/App/Sources/Presentation/Login/View/LoginNicknameView.swift
  Projects/App/Sources/Presentation/MyPage/MyAccountInfo.swift
  Projects/App/Sources/Presentation/MyPage/SettingView.swift
  Tuist/ProjectDescriptionHelpers/Target+Templates.swift
Labels: 🪄Feat, 😎Refactor, ✨Fix, 🐶서연

#133 Fix: 기록하기 뷰 에러 해결
  Projects/App/Sources/DesignSystem/Common/ProgressView.swift
  Projects/App/Sources/DesignSystem/DismissKeyBoard/DismissKeyboard.swift
  Projects/App/Sources/DesignSystem/DismissKeyBoard/DismissKeyboardDemo.swift
  Projects/App/Sources/Presentation/Record/Architectures/RecordViewModel.swift
  Projects/App/Sources/Presentation/Record/Views/RecordCompletionView.swift
  Projects/App/Sources/Presentation/Record/Views/RecordOrganizeView.swift
  Projects/App/Sources/Presentation/Record/Views/RecordStartView.swift
  Projects/App/Sources/SYMApp.swift
Labels: ✨Fix, 🦊민근

#134 Refact: 기록 가능 날짜 변경, 날짜 변경에 따른 UI 변경
  Projects/App/Sources/DesignSystem/Common/RecordView.swift
  Projects/App/Sources/Presentation/Calendar/View/CalendarDetailView.swift
  Projects/App/Sources/Presentation/Calendar/View/CalendarMainView.swift
  Projects/App/Sources/Presentation/Calendar/View/CalendarRecordView.swift
  Projects/App/Sources/Presentation/Calendar/ViewModel/CalendarViewModel.swift
  Projects/App/Sources/Presentation/MyPage/MypageView.swift
  Projects/App/Sources/Presentation/Record/Views/RecordStartView.swift
Labels: 🪄Feat, 😎Refactor, 🐼지영

#136 Refactor: TextEditor 안눌림 해결 + 키보드 time out 해결, gpt응답메시지 Completion -> Combine으로 리팩토링, 기록보기 뷰 뒤로가기 제스처 기능
  Projects/App/Resources/GoogleService-Info.plist
  Projects/App/Sources/DesignSystem/Form/TextEditor.swift
  Projects/App/Sources/Presentation/Record/Architectures/RecordRepository.swift
  Projects/App/Sources/Presentation/Record/Architectures/RecordUseCase.swift
  Projects/App/Sources/Presentation/Record/Architectures/RecordViewModel.swift
  Projects/App/Sources/Presentation/Record/Views/RecordOrganizeView.swift
  Projects/App/Sources/Presentation/Record/Views/RecordStartView.swift
Labels: 😎Refactor, 🦊민근

#139 Fix: calendarRecordView의 기록보러가기 버튼에서 데이터 fetch
  Projects/App/Sources/Presentation/Calendar/View/CalendarDetailView.swift
  Projects/App/Sources/Presentation/Calendar/View/CalendarMainView.swift
  Projects/App/Sources/Presentation/Calendar/View/CalendarRecordView.swift
  Projects/App/Sources/Presentation/Calendar/ViewModel/CalendarViewModel.swift
Labels: ✨Fix, 🐼지영

#147 Feat: 기록보기 뷰에서 기록 편집 중 뒤로가기 버튼을 누르거나 뒤로가기 제스처 를 할 때의 팝업 메시지와 로직 구현
  Projects/App/Sources/DesignSystem/Common/CustomNavigationBar.swift
  Projects/App/Sources/DesignSystem/Form/TextEditor.swift
  Projects/App/Sources/Presentation/Record/Views/RecordOrganizeView.swift
Labels: 🪄Feat, 🗿민석

#149 Design, fix: 로그인 및 회원가입, 앱 실행시 보이는 프로그래스뷰 수정 및 구현완료
  Projects/App/Resources/Assets.xcassets/Login/Splash.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/Login/Splash.imageset/Splash.png
  Projects/App/Resources/Assets.xcassets/Login/Splash.imageset/Splash@2x.png
  Projects/App/Resources/Assets.xcassets/Login/Splash.imageset/Splash@3x.png
  Projects/App/Sources/Presentation/Authencation/AuthenticatedView.swift
  Projects/App/Sources/Presentation/Authencation/AuthenticatedViewModel.swift
  Projects/App/Sources/Presentation/Login/LoginProgressView.swift
  Projects/App/Sources/Presentation/Login/ProgressViewSample.swift
  Projects/App/Sources/Presentation/Login/SplashView.swift
  Projects/App/Sources/Presentation/Login/View/LoginIntroView.swift
  Projects/App/Sources/Presentation/Login/View/MovingSimiView.swift
  Projects/App/Sources/Presentation/MyPage/SettingView.swift
Labels: ✨Fix, 🐶서연, 🎨Design

#151 Refactor: 마이페이지 카드 뷰 분리, gpt token 수 조정 Oz/#137
  Projects/App/Sources/Presentation/MyPage/MyPageCardView.swift
  Projects/App/Sources/Presentation/MyPage/MypageView.swift
  Projects/App/Sources/Presentation/Record/Architectures/RecordUseCase.swift
  Projects/App/Sources/Presentation/Record/Views/RecordCompletionView.swift
  Projects/App/Sources/Services/ChatGPT/ChatGPTManager.swift
Labels: 😎Refactor, 🙊상필

#150 Refactor: Kakao SPM 분리
  Projects/App/Project.swift
  Projects/FirebaseSPM/Project.swift
  Projects/KakaoSPM/Project.swift
  Workspace.swift
Labels: 😎Refactor, 🐶서연

#178 Fix, Refact: 캘린더 드래그 제스처 변경, 캘린더뷰, 뷰모델 리팩토링
  Projects/App/Sources/Presentation/Calendar/View/CalendarDetailView.swift
  Projects/App/Sources/Presentation/Calendar/View/CalendarMainView.swift
  Projects/App/Sources/Presentation/Calendar/View/CalendarRecordView.swift
  Projects/App/Sources/Presentation/Calendar/View/DatePicker.swift
  Projects/App/Sources/Presentation/Calendar/ViewModel/CalendarViewModel.swift
Labels: 😎Refactor, ✨Fix, 🗿민석, 🐼지영
