Repository Good-MoGong/SYM, pull requests merged in 2024-02, with the labels that each got.

#68 fix, feat: popup 컴포넌트 수정 및 애니메이션 추가
  Projects/App/Sources/DesignSystem/CustomAlert/PopupViewModifier+Extension.swift
Labels: 🪄Feat, ✨Fix, 🐶서연

#64 feat: 마이페이지 뷰 추가, 커스텀 네비게이션 바 추가 #41
  Projects/App/Sources/DesignSystem/Button/Button.swift
  Projects/App/Sources/DesignSystem/Common/CommonDemo.swift
  Projects/App/Sources/DesignSystem/Common/CustomNavigationBar.swift
  Projects/App/Sources/DesignSystem/Common/RecordView.swift
  Projects/App/Sources/DesignSystem/Common/TextFieldClearButton.swift
  Projects/App/Sources/Presentation/MyPage/MyAccountInfo.swift
  Projects/App/Sources/Presentation/MyPage/MypageDemo.swift
  Projects/App/Sources/Presentation/MyPage/MypageView.swift
  Projects/App/Sources/Presentation/MyPage/SettingView.swift
  Projects/App/Sources/Presentation/Tab/MainTab.swift
  Projects/App/Sources/Presentation/Tab/MainView.swift
Labels: 🪄Feat, 🙊상필

#65 fix: 기록 보기 뷰에서 아이폰 해상도 별 Padding 조절 함수 수정
  Projects/App/Sources/Presentation/Record/RecordOrganizeView.swift
Labels: ✨Fix, 🗿민석

#72 refactor: Tuist 의존성 방식 Xcode SPM으로 변경
  Projects/App/Project.swift
  Projects/FirebaseSPM/Project.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  Tuist/ProjectDescriptionHelpers/SPM+Dependencies.swift
  Tuist/ProjectDescriptionHelpers/Target+Templates.swift
Labels: 😎Refactor, 🐶서연

#73 fix: 애플 로그인 버튼 디자인 수정
  Projects/App/Sources/Presentation/Login/View/LoginIntroView.swift
  Projects/App/Sources/Presentation/Login/View/LoginNicknameView.swift
  Projects/App/Sources/Presentation/Tab/MainView.swift
Labels: ✨Fix, 🐶서연

#69 Feat: 기록하기 뷰 생성
  Projects/App/Resources/Assets.xcassets/Character/RecordBackground.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/Character/RecordBackground.imageset/recordbackgorund 1.png
  Projects/App/Resources/Assets.xcassets/Character/RecordBackground.imageset/recordbackgorund 2.png
  Projects/App/Resources/Assets.xcassets/Character/RecordBackground.imageset/recordbackgorund.png
  Projects/App/Resources/Assets.xcassets/Character/Sample.imageset/Sample.png
  Projects/App/Resources/Assets.xcassets/Character/Sample.imageset/Sample@2x.png
  Projects/App/Resources/Assets.xcassets/Character/Sample.imageset/Sample@3x.png
  Projects/App/Resources/Assets.xcassets/Character/SimiCurious.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/Character/SimiCurious.imageset/SimiCurious 1.png
  Projects/App/Resources/Assets.xcassets/Character/SimiCurious.imageset/SimiCurious 2.png
  Projects/App/Resources/Assets.xcassets/Character/SimiCurious.imageset/SimiCurious.png
  Projects/App/Resources/Assets.xcassets/Character/SimiSad.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/Character/SimiSad.imageset/SimiSad 1.png
  Projects/App/Resources/Assets.xcassets/Character/SimiSad.imageset/SimiSad 2.png
  Projects/App/Resources/Assets.xcassets/Character/SimiSad.imageset/SimiSad.png
  Projects/App/Resources/Assets.xcassets/Character/SimiSad2.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/Character/SimiSad2.imageset/SimiSad2 1.png
  Projects/App/Resources/Assets.xcassets/Character/SimiSad2.imageset/SimiSad2 2.png
  Projects/App/Resources/Assets.xcassets/Character/SimiSad2.imageset/SimiSad2.png
  Projects/App/Resources/Assets.xcassets/Character/SimiSmile.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/Character/SimiSmile.imageset/SimiSmile 1.png
  Projects/App/Resources/Assets.xcassets/Character/SimiSmile.imageset/SimiSmile 2.png
  Projects/App/Resources/Assets.xcassets/Character/SimiSmile.imageset/SimiSmile.png
  Projects/App/Resources/Assets.xcassets/Character/SimiSmile2.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/Character/SimiSmile2.imageset/SimiSmile2 1.png
  Projects/App/Resources/Assets.xcassets/Character/SimiSmile2.imageset/SimiSmile2 2.png
  Projects/App/Resources/Assets.xcassets/Character/SimiSmile2.imageset/SimiSmile2.png
  Projects/App/Sources/DesignSystem/ChatBubble/ChatBubble.swift
  Projects/App/Sources/DesignSystem/Common/RecordView.swift
  Projects/App/Sources/Extensions/CGFloatExtension.swift
  Projects/App/Sources/Presentation/Login/Splash/SplashView.swift
  Projects/App/Sources/Presentation/Login/View/LoginIntroView.swift
  Projects/App/Sources/Presentation/MyPage/MyAccountInfo.swift
  Projects/App/Sources/Presentation/Record/RecordCompletionView.swift
  Projects/App/Sources/Presentation/Record/RecordDemo.swift
  Projects/App/Sources/Presentation/Record/RecordOrganizeView.swift
  Projects/App/Sources/Presentation/Record/RecordStartView.swift
  Projects/App/Sources/Presentation/Record/RecordViewModel.swift
Labels: 🪄Feat, 🦊민근

#78 Feat: 토스트뷰 컴포넌트 구현
  Projects/App/Sources/DesignSystem/Toast/Toast.swift
  Projects/App/Sources/DesignSystem/Toast/ToastModifier.swift
  Projects/App/Sources/DesignSystem/Toast/ToastView.swift
  Projects/App/Sources/Presentation/Record/RecordStartView.swift
  Projects/App/Sources/Presentation/Record/RecordViewModel.swift
Labels: 🪄Feat, 🦊민근

#92 feat: Apple, 카카오 로그인 구현완료
  Projects/App/Project.swift
  Projects/App/Sources/Data/Repositories/DIContainer.swift
  Projects/App/Sources/DesignSystem/Font/Font.swift
  Projects/App/Sources/Domain/UseCases/Protocol/Services/AuthenticationService.swift
  Projects/App/Sources/Domain/UseCases/Protocol/Services/FirebaseService.swift
  Projects/App/Sources/Domain/UseCases/Protocol/Services/Services.swift
  Projects/App/Sources/Model/Diary.swift
  Projects/App/Sources/Model/User.swift
  Projects/App/Sources/Presentation/Authencation/AuthenticatedView.swift
  Projects/App/Sources/Presentation/Authencation/AuthenticatedViewModel.swift
  Projects/App/Sources/Presentation/Login/View/LoginIntroView.swift
  Projects/App/Sources/Presentation/Login/View/LoginNicknameView.swift
  Projects/App/Sources/Presentation/MyPage/SettingView.swift
  Projects/App/Sources/SYMApp.swift
  Projects/App/Support/Info.plist
  Projects/FirebaseSPM/Project.swift
  Projects/KakaoSPM/Project.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  Tuist/ProjectDescriptionHelpers/SPM+Dependencies.swift
  Tuist/ProjectDescriptionHelpers/SPM+TargetDependency.swift
  Tuist/ProjectDescriptionHelpers/Script.swift
  Tuist/ProjectDescriptionHelpers/Target+Templates.swift
Labels: 🪄Feat, 🎉Backend, 🐶서연

#91 Feat, Fix, Docs: CustomDatePicker 구현, KeyPathExtension 호환성 개선, Tuist iOS 버전 변경(16.4)
  Projects/App/Sources/Extensions/KeyPathExtension.swift
  Projects/App/Sources/Presentation/Calendar/View/CalendarDetailView.swift
  Projects/App/Sources/Presentation/Calendar/View/DatePicker.swift
  Tuist/ProjectDescriptionHelpers/Target+Templates.swift
Labels: 📃Docs, 🪄Feat, ✨Fix, 🗿민석

#96 hotFix: Tusit 버전 미반영 부분 수정
  Projects/App/Project.swift
  Projects/FirebaseSPM/Project.swift
Labels: 🚨HotFix, 🐶서연

#98 Feat: CalenderView Gesture 이동 제한 조건 설정과 Picker 이동과의 상태 연동
  Projects/App/Sources/Presentation/Calendar/View/CalendarDetailView.swift
  Projects/App/Sources/Presentation/Calendar/View/DatePicker.swift
Labels: 🪄Feat, 🗿민석

#106 Feat: 카카오톡 로그인 탈퇴 구현 완료
  Projects/App/Sources/Domain/UseCases/Protocol/Services/AuthenticationService.swift
  Projects/App/Sources/Domain/UseCases/Protocol/Services/FirebaseService.swift
  Projects/App/Sources/Presentation/Authencation/AuthenticatedViewModel.swift
  Projects/App/Sources/Presentation/MyPage/SettingView.swift
  Projects/App/Sources/Presentation/Record/Views/RecordDemo.swift
Labels: 🪄Feat, 🎉Backend, 🐶서연

#109 Feat: Firebase에 기록 저장 구현
  Projects/App/Resources/SYMCoreData.xcdatamodeld/SYMCoreData.xcdatamodel/contents
  Projects/App/Sources/Data/Repositories/DiaryEntity+CoreDataProperties.swift
  Projects/App/Sources/Presentation/Record/Architectures/RecordEnum.swift
  Projects/App/Sources/Presentation/Record/Architectures/RecordRepository.swift
  Projects/App/Sources/Presentation/Record/Architectures/RecordUseCase.swift
  Projects/App/Sources/Presentation/Record/Architectures/RecordViewModel.swift
  Projects/App/Sources/Presentation/Record/Views/RecordDemo.swift
  Projects/App/Sources/Presentation/Record/Views/RecordStartView.swift
  Projects/App/Sources/Presentation/Tab/MainTab.swift
  Projects/App/Sources/Services/Firebase/FirebaseManager.swift
  Projects/App/Sources/Services/Firebase/ServicesDemo.swift
  Tuist/ProjectDescriptionHelpers/Target+Templates.swift
Labels: 🪄Feat, 🦊민근

#111 feat: 애플 로그인 탈퇴 구현 완료
  .gitignore
  Projects/App/Sources/Domain/UseCases/Protocol/Services/AuthenticationService.swift
  Projects/App/Sources/Domain/UseCases/Protocol/Services/FirebaseService.swift
  Projects/App/Sources/Presentation/Authencation/AuthenticatedViewModel.swift
  Projects/App/Sources/Presentation/MyPage/SettingView.swift
  firebase.json
Labels: 🪄Feat, 🎉Backend, 🐶서연

#110 Refact: 닉네임이 사용되는 View에서 닉네임이 변경 되었을 때 반영, 닉네임 변경 후 완료 버튼 누르면 dismiss
  Projects/App/Sources/DesignSystem/Common/RecordView.swift
  Projects/App/Sources/Presentation/Authencation/AuthenticatedViewModel.swift
  Projects/App/Sources/Presentation/Calendar/View/CalendarDetailView.swift
  Projects/App/Sources/Presentation/Calendar/View/CalendarMainView.swift
  Projects/App/Sources/Presentation/Login/View/LoginNicknameView.swift
  Projects/App/Sources/Presentation/MyPage/MyAccountInfo.swift
  Projects/App/Sources/Presentation/MyPage/MypageView.swift
Labels: 😎Refactor, 🗿민석, 🐼지영
