Repository Good-MoGong/SYM, pull requests merged in 2024-01, with the labels that each got.

#20 feat: Font, Color 디자인 시스템 추가
  Projects/App/SYM.xcodeproj/project.pbxproj
  Projects/App/Sources/DesignSystem/Button/ButtonDemo.swift
  Projects/App/Sources/DesignSystem/Color/Color.swift
  Projects/App/Sources/DesignSystem/Font/Font.swift
  Projects/App/Sources/DesignSystem/Font/FontDemo.swift
  Projects/FirebaseSPM/FirebaseSPM.xcodeproj/project.pbxproj
  SYM.xcworkspace/contents.xcworkspacedata
  Tuist/Dependencies.swift
Labels: 🪄Feat, 🙊상필

#27 feat: PopupView 컴포넌트 생성 및 파일명,코드 수정
  Projects/App/SYM.xcodeproj/project.pbxproj
  Projects/App/Sources/DesignSystem/CustomAlert/AlertDemo.swift
  Projects/App/Sources/DesignSystem/CustomAlert/PopupViewDemo.swift
  Projects/App/Sources/DesignSystem/CustomAlert/PopupViewModifier+Extension.swift
  Projects/FirebaseSPM/FirebaseSPM.xcodeproj/project.pbxproj
  SYM.xcworkspace/contents.xcworkspacedata
Labels: 🪄Feat, 🐶서연

#30 feat: Button 컴포넌트 생성
  Projects/App/SYM.xcodeproj/project.pbxproj
  Projects/App/Sources/DesignSystem/Button/ButtonDemo.swift
  Projects/FirebaseSPM/FirebaseSPM.xcodeproj/project.pbxproj
  SYM.xcworkspace/contents.xcworkspacedata
Labels: 🪄Feat, 🐼지영

#31 feat, refactor: TextField, TextEditor 관련 컴포넌트 구현과 버튼 컴포넌트 파일 분리
  Projects/App/SYM.xcodeproj/project.pbxproj
  Projects/App/Sources/DesignSystem/Button/Button.swift
  Projects/App/Sources/DesignSystem/Button/ButtonDemo.swift
  Projects/App/Sources/DesignSystem/CustomAlert/PopupViewModifier+Extension.swift
  Projects/App/Sources/DesignSystem/Form/FormDemo.swift
  Projects/App/Sources/DesignSystem/Form/TextEditor.swift
  Projects/App/Sources/DesignSystem/Form/TextField.swift
  Projects/FirebaseSPM/FirebaseSPM.xcodeproj/project.pbxproj
  SYM.xcworkspace/contents.xcworkspacedata
Labels: 🪄Feat, 🐶서연

#36 feat: 말풍선 뷰 컴포넌트 생성 및 레거시 폰트 삭제
  Projects/App/Sources/DesignSystem/ChatBubble/ChatBubble.swift
  Projects/App/Sources/DesignSystem/ChatBubble/ChatBubbleDemo.swift
  Projects/App/Sources/DesignSystem/Color/Color.swift
  Projects/App/Sources/DesignSystem/Font/Font.swift
  Projects/App/Sources/DesignSystem/Form/TextEditor.swift
  Projects/App/Sources/DesignSystem/Form/TextField.swift
Labels: 🪄Feat, 😎Refactor, 🦊민근

#37 feat, refactor: 회원 가입뷰 구현, 컴포넌트 수정, swiftLint 수정
  Projects/App/Scripts/.swiftlint.yml
  Projects/App/Scripts/SwiftLintRunScript.sh
  Projects/App/Sources/Data/Network/NetworkDemo.swift
  Projects/App/Sources/Data/Repositories/RepoDemo.swift
  Projects/App/Sources/DesignSystem/Button/Button.swift
  Projects/App/Sources/DesignSystem/Button/ButtonDemo.swift
  Projects/App/Sources/DesignSystem/Color/ColorDemo.swift
  Projects/App/Sources/DesignSystem/CustomAlert/PopupViewDemo.swift
  Projects/App/Sources/DesignSystem/CustomAlert/PopupViewModifier+Extension.swift
  Projects/App/Sources/DesignSystem/Form/TextEditor.swift
  Projects/App/Sources/DesignSystem/Form/TextField.swift
  Projects/App/Sources/Presentation/Sign/View/SignDemo.swift
  Projects/App/Sources/Presentation/Sign/View/SignupNicknameView.swift
  Projects/App/Sources/Presentation/Sign/View/SignupView.swift
  Projects/App/Sources/SYMApp.swift
Labels: 🪄Feat, 😎Refactor, 🐶서연

#39 feat: 커스텀 탭바 구현
  Projects/App/Sources/Presentation/MainView.swift
Labels: 🪄Feat, 🐶서연

#46 feat, refactor: Form, Popup 컴포넌트 수정, SignUpNicknameView 리팩토링
  Projects/App/Sources/DesignSystem/Color/Color.swift
  Projects/App/Sources/DesignSystem/Common/BackgroundColor.swift
  Projects/App/Sources/DesignSystem/CustomAlert/PopupViewDemo.swift
  Projects/App/Sources/DesignSystem/CustomAlert/PopupViewModifier+Extension.swift
  Projects/App/Sources/DesignSystem/Font/Font.swift
  Projects/App/Sources/DesignSystem/Font/FontDemo.swift
  Projects/App/Sources/DesignSystem/Form/FormDemo.swift
  Projects/App/Sources/DesignSystem/Form/TextEditor.swift
  Projects/App/Sources/DesignSystem/Form/TextField.swift
  Projects/App/Sources/Presentation/Sign/View/SignupNicknameView.swift
  Projects/App/Sources/Presentation/Sign/View/SignupView.swift
Labels: 🪄Feat, 😎Refactor, 🐶서연

#45 Feat: button 컴포넌트 수정
  Projects/App/Sources/DesignSystem/Button/Button.swift
  Projects/App/Sources/DesignSystem/Color/Color.swift
  Tuist/Dependencies.swift
Labels: 😎Refactor, 🐼지영

#50 feat: 색상 컴포넌트 수정
  Projects/App/Sources/DesignSystem/Button/Button.swift
  Projects/App/Sources/DesignSystem/ChatBubble/ChatBubble.swift
  Projects/App/Sources/DesignSystem/Color/Color.swift
  Projects/App/Sources/DesignSystem/Color/ColorDemo.swift
  Projects/App/Sources/DesignSystem/Common/BackgroundColor.swift
  Projects/App/Sources/DesignSystem/CustomAlert/PopupViewModifier+Extension.swift
  Projects/App/Sources/DesignSystem/Form/TextField.swift
  Projects/App/Sources/Presentation/Sign/View/SignupNicknameView.swift
  Projects/App/Sources/Presentation/Tab/MainTab.swift
  Projects/App/Sources/Presentation/Tab/MainView.swift
  Projects/App/Sources/Presentation/Tab/TestTabView.swift
Labels: 🪄Feat, 😎Refactor, 🐶서연

#52 Feat, Refact: Color 컴포넌트 수정 및 Button 컴포넌트 수정
  Projects/App/Sources/DesignSystem/Button/Button.swift
  Projects/App/Sources/DesignSystem/Button/ButtonDemo.swift
  Projects/App/Sources/DesignSystem/Color/Color.swift
  Projects/App/Sources/Presentation/Tab/TestTabView.swift
Labels: 🪄Feat, 😎Refactor, 🐼지영

#58 hotFix: 네이밍 변경으로 인한 빌드 오류 수정
  Projects/App/Resources/Assets.xcassets/Tabbar/Contents.json
  Projects/App/Sources/DesignSystem/CustomAlert/CommonDoubleBtnView.swift
  Projects/App/Sources/Presentation/Tab/MainTab.swift
  Projects/App/Sources/Presentation/Tab/TabBarView.swift
Labels: 🚨HotFix, 🐶서연

#63 feat: 애플 로그인 구현
  Projects/App/Resources/Assets.xcassets/Character/Contents.json
  Projects/App/Resources/Assets.xcassets/Character/Sample.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/Character/Sample.imageset/Sample.png
  Projects/App/Resources/Assets.xcassets/Character/Sample.imageset/Sample@2x.png
  Projects/App/Resources/Assets.xcassets/Character/Sample.imageset/Sample@3x.png
  Projects/App/Resources/Assets.xcassets/SignLogo/AppleLogo.imageset/AppleLogo.png
  Projects/App/Resources/Assets.xcassets/SignLogo/AppleLogo.imageset/AppleLogo@2x.png
  Projects/App/Resources/Assets.xcassets/SignLogo/AppleLogo.imageset/AppleLogo@3x.png
  Projects/App/Resources/Assets.xcassets/SignLogo/AppleLogo.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/SignLogo/Contents.json
  Projects/App/Resources/Assets.xcassets/SignLogo/KaKaoLogo.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/SignLogo/KaKaoLogo.imageset/KaKaoLogo.png
  Projects/App/Resources/Assets.xcassets/SignLogo/KaKaoLogo.imageset/KaKaoLogo@2x.png
  Projects/App/Resources/Assets.xcassets/SignLogo/KaKaoLogo.imageset/KaKaoLogo@3x.png
  Projects/App/Resources/Assets.xcassets/TestImage.imageset/007PetListPicBorder.png
  Projects/App/SYM.entitlements
  Projects/App/Sources/DesignSystem/Font/Font.swift
  Projects/App/Sources/Domain/UseCases/DIContainerUseCase.swift
  Projects/App/Sources/Domain/UseCases/Protocol/ProtocolDemo.swift
  Projects/App/Sources/Domain/UseCases/Protocol/Services/AuthenticationService.swift
  Projects/App/Sources/Domain/UseCases/Protocol/Services/ServiceError.swift
  Projects/App/Sources/Domain/UseCases/Protocol/Services/Services.swift
  Projects/App/Sources/Domain/UseCases/UseCaseDemo.swift
  Projects/App/Sources/Model/Diary.swift
  Projects/App/Sources/Model/User.swift
  Projects/App/Sources/Presentation/Authencation/AuthenticatedView.swift
  Projects/App/Sources/Presentation/Authencation/AuthenticatedViewModel.swift
  Projects/App/Sources/Presentation/Login/Splash/SplashView.swift
  Projects/App/Sources/Presentation/Login/View/LoginIntroView.swift
  Projects/App/Sources/Presentation/Login/View/LoginNicknameView.swift
  Projects/App/Sources/Presentation/Login/ViewModel/ViewModelDemo.swift
  Projects/App/Sources/Presentation/Sign/View/SignupView.swift
  Projects/App/Sources/SYMApp.swift
  Projects/App/Sources/Util/RandomNonceString.swift
  Projects/App/Sources/Util/SHA256.swift
  Tuist/ProjectDescriptionHelpers/Target+Templates.swift
Labels: 🪄Feat, 🐶서연
